blank_issues_enabled: false
contact_links:
  - name: Documentation Website
    url: https://plugins.javalent.com/home
    about: The place for the most up-to-date documentation for anything Javalent.
  - name: Documentation Website repository
    url: https://github.com/javalent/Javalents-Plugins/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
    about: Need to report an issue to documentation? Please do so here!
  - name: Discord Support
    url: https://discord.gg/obsidianmd
    about: Visit Javalent-Support-Thread to talk to a human and get some help.
  - name: Feature Requests
    url: https://discord.gg/obsidianmd
    about: Visit Javalent-Support-Thread to pose your idea. If its accepted, it will be made into an issue.
 
